### PR TITLE
French translation of ArtyFx and Luppp's manuals

### PR DESCRIPTION
**Pull request by sub26nico**
Hi Harry, olinuxx and I have worked on the french translation of the ArtyFx luppp's manual.
 I hope it can be useful.

### CODE REVIEW

**Comment by harryhaaren** [comment]
I'm looking at the latest 3 commits - a few thoughts;
- How are the FR translations being updated? I see those two commits change a lot of content - and seeming back again... was this just a mistake or am I missing something?
- We shouldn't change the luppp (non-FR) version in this Pull-Request, it makes it hard to merge and keep content in sync.

**Comment by sub26nico** [comment]
@harryhaaren ,maybe I  made a mistake, I'm just a newbie on github,
I just tried to update my fork...sorry for that. I'll find a solution as soon as possible.

**Comment by trebmuh** [comment]
@harryhaaren : re the luppp non-FR, IIRC the changes in this PR are there to reflect the changes in the master branch since it changes between the time sub26nico forked the repo and the time he committed this PR. That was done to resolve a merge conflict signaled by github. Hence there is no change to luppp non-FR with this commit.

**Comment by harryhaaren** [comment]
ah ok - I need to spend some time to review this properly - will try find time at the weekend! Will keep you posted on progress, -H

**Comment by trebmuh** [comment]
Sweet.

**Comment by harryhaaren** [comment]
Pulled these commits into a `fr` branch, added the `fr-beginner.rst` pull request, and pushed content to `fr` branch. Please see here for intended workflow: https://github.com/openAVproductions/openAV-manual/issues/1#issuecomment-298191468

Thanks for all this great work! -Harry

**Pull request closed without merging**
