### PR TITLE
adds mention to the volume level selection

### PR DESCRIPTION
**Pull request by trebmuh**
This functionality isn't obvious but is useful since the default volume is quite strong.

### CODE REVIEW

**Comment by sub26nico** [comment]
Add my voice here. I found how to change the volume of the metronome a few days ago but 
for more control, I use non mixer between the 'headphone out' of Luppp and 
the system outputs .

**Comment by trebmuh** [comment]
:+1:

**Comment by harryhaaren** [comment]
And pushed to the manual online at http://openavproductions.com/doc/luppp.html

**Comment by trebmuh** [comment]
re- :+1:  then :)

**Pull request merged**
