### PR TITLE
Merge German luppp translation

### PR DESCRIPTION
**Pull request by coderkun**
It doesn’t seem that @georgkrause is finishing and merging his German translations so I would like to merge my work on the German translation for luppp.

### CODE REVIEW

**Comment by harryhaaren** [comment]
Hi @coderkun, no objection here. Would you rebase it please? Currently the code doesn't apply cleanly, and with the translations I find merging difficult because I'm not native in the language :D I'll try pull this weekend if ready to merge then. Thanks, -H

**Comment by coderkun** [comment]
@harryhaaren, it looks like this code has already been merged into the upstream branch “de”. So this PR is a duplicate and I can delete/close it, right?

**Comment by harryhaaren** [comment]
Yes correct - I tend to use the "Rebase and Merge" method (keeps the git history cleaner..) but then I should also mark this as closed - otherwise this ambigous situation occurs that Github doesn't know I merged it, because the commit SHAs are different.. thanks for pointing that out - I'll be more careful with this in future.

Thanks for the work on this again (everybody) :)

**Comment by coderkun** [comment]
I will also make sure to squash the commits into one for further PRs. Thanks for *your* work ;)

**Comment by harryhaaren** [comment]
No need to squash all commits into one - makes it harder to review the changes. Commits at the size in this PR are perfect :)

**Pull request closed without merging**
